apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ecnf-gbk-2
  name: gbk-ecnf-2
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ecnf-gbk-2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ecnf-gbk-2
    spec:
      nodeSelector:
              ppcinder-csi: enabled
      containers:
        - image: 'hub.ecns.io/library/gbk-ecnf:v1'
          imagePullPolicy: IfNotPresent
          command:
            - sleep
            - 10d
          name: container1
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          volumeMounts:
            - mountPath: "/okkk"
              name: pp-cinder
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: pp-cinder
          persistentVolumeClaim:
             claimName: ppcluster-cinder
